Erte pdf
Laia42/PES_INFOVID-19 pull request #6
Opened 2020-10-24 10:36 UTC by carlesll

- Diferent fixes in the UI
- Add a back button
- Add a send button
- You can send the information throught internet using the email appi
- You can save your text in a drive

2020-10-24 17:05 UTC, Anvii8 approved these changes

2020-10-25 09:27 UTC, sergibosquet approved these changes

2020-10-25 09:56 UTC, Anvii8 requested changes
No se ve donde se guarda el fichero pdf, he buscado la ruta, que me ha costado lo suyo, y no hay nada

2020-10-25 10:55 UTC, Laia42 approved these changes
When the mail is send, the "to" field is filled with the user email, however in the "from" field this doesn't happen. There's a way to fill the "from" field with the user email too? This way i just have to click the send button and that's it.

2020-10-26 14:27 UTC, sergibosquet approved these changes

2020-10-26 18:24 UTC, merged